/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.TelasNovo;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Djair Maykon
 */
public class TNovoProducao extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form TNovoPedido
     */
    public TNovoProducao() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLCodigoProducao = new javax.swing.JLabel();
        jTFCodigoProducao = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLCodigoPedido = new javax.swing.JLabel();
        jTFCodigoPedido = new javax.swing.JTextField();
        jBProcurarPedido = new javax.swing.JButton();
        jLSituacao = new javax.swing.JLabel();
        jCBSituacao = new javax.swing.JComboBox<>();
        jLData = new javax.swing.JLabel();
        jDCDataDaProducao = new com.toedter.calendar.JDateChooser();
        jBSalvar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLCodigodaTinta = new javax.swing.JLabel();
        jTFCodigoTinta = new javax.swing.JTextField();
        jBProcurarTinta = new javax.swing.JButton();
        jLQtdProducao = new javax.swing.JLabel();
        jTFQuantidadeProducao = new javax.swing.JTextField();
        jTFCustoProducao = new javax.swing.JTextField();
        jLCustoProducao = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(57, 93, 117));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLCodigoProducao.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLCodigoProducao.setLabelFor(jTFCodigoProducao);
        jLCodigoProducao.setText("Código da Produção:");

        jTFCodigoProducao.setEditable(false);
        jTFCodigoProducao.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLCodigoPedido.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLCodigoPedido.setLabelFor(jTFCodigoPedido);
        jLCodigoPedido.setText("Código do Pedido:");

        jTFCodigoPedido.setEditable(false);
        jTFCodigoPedido.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jBProcurarPedido.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jBProcurarPedido.setText("...");
        jBProcurarPedido.setBorder(null);

        jLSituacao.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLSituacao.setText("Situação:");

        jCBSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em andamento", "Finalizada" }));

        jLData.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLData.setLabelFor(jTFCodigoProducao);
        jLData.setText("Data:");

        jDCDataDaProducao.setEnabled(false);

        jBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/37.png"))); // NOI18N
        jBSalvar.setText("Salvar");

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Delete_01.png"))); // NOI18N
        jBCancelar.setText("Cancelar");

        jLCodigodaTinta.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLCodigodaTinta.setLabelFor(jTFCodigoPedido);
        jLCodigodaTinta.setText("Código da Tinta:");

        jTFCodigoTinta.setEditable(false);
        jTFCodigoTinta.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jBProcurarTinta.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jBProcurarTinta.setText("...");
        jBProcurarTinta.setBorder(null);

        jLQtdProducao.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLQtdProducao.setLabelFor(jTFCodigoProducao);
        jLQtdProducao.setText("Quantidade:");

        jTFQuantidadeProducao.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jTFCustoProducao.setEditable(false);
        jTFCustoProducao.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLCustoProducao.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLCustoProducao.setLabelFor(jTFCodigoProducao);
        jLCustoProducao.setText("Custo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLSituacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLQtdProducao)
                            .addComponent(jLCodigoPedido)
                            .addComponent(jLCodigodaTinta))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTFCodigoTinta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBProcurarTinta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTFCodigoPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBProcurarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTFQuantidadeProducao, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLCodigoProducao)
                                    .addGap(26, 26, 26))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLData)
                                    .addGap(110, 110, 110)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLCustoProducao)
                                .addGap(120, 120, 120)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFCodigoProducao)
                            .addComponent(jDCDataDaProducao, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(jTFCustoProducao))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jBSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCodigoProducao)
                            .addComponent(jTFCodigoProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDCDataDaProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCustoProducao)
                            .addComponent(jTFCustoProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCodigoPedido)
                            .addComponent(jTFCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBProcurarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCodigodaTinta)
                            .addComponent(jTFCodigoTinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBProcurarTinta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLQtdProducao)
                            .addComponent(jTFQuantidadeProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSituacao)
                            .addComponent(jCBSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCancelar))
                    .addComponent(jSeparator2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjBCancelar() {
        return jBCancelar;
    }

    public JButton getjBProcurarPedido() {
        return jBProcurarPedido;
    }

    public JButton getjBProcurarTinta() {
        return jBProcurarTinta;
    }

    public JButton getjBSalvar() {
        return jBSalvar;
    }

    public JComboBox<String> getjCBSituacao() {
        return jCBSituacao;
    }

    public JDateChooser getjDCDataDaProducao() {
        return jDCDataDaProducao;
    }

    public JTextField getjTFCodigoPedido() {
        return jTFCodigoPedido;
    }

    public JTextField getjTFCodigoProducao() {
        return jTFCodigoProducao;
    }

    public JTextField getjTFCodigoTinta() {
        return jTFCodigoTinta;
    }

    public JTextField getjTFCustoProducao() {
        return jTFCustoProducao;
    }

    public JTextField getjTFQuantidadeProducao() {
        return jTFQuantidadeProducao;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBProcurarPedido;
    private javax.swing.JButton jBProcurarTinta;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JComboBox<String> jCBSituacao;
    private com.toedter.calendar.JDateChooser jDCDataDaProducao;
    private javax.swing.JLabel jLCodigoPedido;
    private javax.swing.JLabel jLCodigoProducao;
    private javax.swing.JLabel jLCodigodaTinta;
    private javax.swing.JLabel jLCustoProducao;
    private javax.swing.JLabel jLData;
    private javax.swing.JLabel jLQtdProducao;
    private javax.swing.JLabel jLSituacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTFCodigoPedido;
    private javax.swing.JTextField jTFCodigoProducao;
    private javax.swing.JTextField jTFCodigoTinta;
    private javax.swing.JTextField jTFCustoProducao;
    private javax.swing.JTextField jTFQuantidadeProducao;
    // End of variables declaration//GEN-END:variables
}
