/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Ferramentas;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Djair Maykon
 */
public class TFerramentasBuscarEndereco extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form TNovoPedido
     */
    public TFerramentasBuscarEndereco() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLCodigoProducao5 = new javax.swing.JLabel();
        jTFCodigoProducao = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLCodigoPedido = new javax.swing.JLabel();
        jTFCodigoPedido = new javax.swing.JTextField();
        jBProcurarPedido = new javax.swing.JButton();
        jLSituacao = new javax.swing.JLabel();
        jCBSituacao = new javax.swing.JComboBox<>();
        jLData = new javax.swing.JLabel();
        jBSalvar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLCodigodaTinta = new javax.swing.JLabel();
        jTFCustoProducao = new javax.swing.JTextField();
        jLCustoProducao = new javax.swing.JLabel();
        jLQtdProducao1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescricaoPedido = new javax.swing.JTextArea();
        jBAdicionarTinta = new javax.swing.JButton();
        jBRemoverTinta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTintasProduzidas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTFCEP = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jLFerramentaCEP = new javax.swing.JLabel();
        jLFerramentaUF = new javax.swing.JLabel();
        jTFFerramentaUF = new javax.swing.JTextField();
        jLFerramentaRua = new javax.swing.JLabel();
        jTFFerramentaBairro = new javax.swing.JTextField();
        jLFerramentaBairro = new javax.swing.JLabel();
        jTFFerramentaRua = new javax.swing.JTextField();
        jLFerramentaNumero = new javax.swing.JLabel();
        jTFFerramentaNumero = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLFerramentaCidade = new javax.swing.JLabel();
        jTFFerramentaCidade = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(57, 93, 117));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLCodigoProducao5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLCodigoProducao5.setText("Código da Produção:");

        jTFCodigoProducao.setEditable(false);
        jTFCodigoProducao.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLCodigoPedido.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLCodigoPedido.setText("Código do Pedido:");

        jTFCodigoPedido.setEditable(false);
        jTFCodigoPedido.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jBProcurarPedido.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jBProcurarPedido.setText("...");
        jBProcurarPedido.setBorder(null);

        jLSituacao.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLSituacao.setText("Situação:");

        jCBSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em andamento", "Finalizada" }));

        jLData.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLData.setText("Data:");

        jBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/37.png"))); // NOI18N
        jBSalvar.setText("Salvar");

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Delete_01.png"))); // NOI18N
        jBCancelar.setText("Cancelar");

        jLCodigodaTinta.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLCodigodaTinta.setText("Código da Tinta:");

        jTFCustoProducao.setEditable(false);
        jTFCustoProducao.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLCustoProducao.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLCustoProducao.setText("Custo:");

        jLQtdProducao1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLQtdProducao1.setText("Descrição:");

        jTADescricaoPedido.setEditable(false);
        jTADescricaoPedido.setColumns(20);
        jTADescricaoPedido.setRows(5);
        jScrollPane1.setViewportView(jTADescricaoPedido);

        jBAdicionarTinta.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jBAdicionarTinta.setText("Adicionar");
        jBAdicionarTinta.setBorder(null);
        jBAdicionarTinta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBRemoverTinta.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jBRemoverTinta.setText("Remover");
        jBRemoverTinta.setBorder(null);
        jBRemoverTinta.setEnabled(false);
        jBRemoverTinta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTTintasProduzidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Custo", "Quantidade"
            }
        ));
        jScrollPane2.setViewportView(jTTintasProduzidas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLSituacao)
                                    .addComponent(jLCodigodaTinta)
                                    .addComponent(jLCodigoPedido)
                                    .addComponent(jLQtdProducao1)
                                    .addComponent(jLData)
                                    .addComponent(jLCustoProducao)
                                    .addComponent(jLCodigoProducao5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFCustoProducao, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCBSituacao, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTFCodigoPedido)
                                        .addGap(6, 6, 6)
                                        .addComponent(jBProcurarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTFCodigoProducao, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jBAdicionarTinta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBRemoverTinta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator1))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jBSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFCodigoProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCodigoProducao5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFCustoProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCustoProducao))
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBProcurarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCodigoPedido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLQtdProducao1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBAdicionarTinta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCodigodaTinta)
                            .addComponent(jBRemoverTinta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLSituacao))))
                .addContainerGap())
        );

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(57, 93, 117));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBBuscar.setText("Buscar CEP");

        jLFerramentaCEP.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLFerramentaCEP.setText("CEP:");

        jLFerramentaUF.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLFerramentaUF.setText("UF:");

        jLFerramentaRua.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLFerramentaRua.setText("Rua:");

        jLFerramentaBairro.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLFerramentaBairro.setText("Bairro:");

        jLFerramentaNumero.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLFerramentaNumero.setText("Numero:");

        jLFerramentaCidade.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLFerramentaCidade.setText("Cidade:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFCEP, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBBuscar))
                    .addComponent(jTFFerramentaUF)
                    .addComponent(jTFFerramentaBairro)
                    .addComponent(jTFFerramentaRua)
                    .addComponent(jTFFerramentaNumero)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLFerramentaCEP)
                            .addComponent(jLFerramentaRua)
                            .addComponent(jLFerramentaBairro)
                            .addComponent(jLFerramentaUF)
                            .addComponent(jLFerramentaNumero)
                            .addComponent(jLFerramentaCidade))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTFFerramentaCidade))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLFerramentaCEP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLFerramentaUF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTFFerramentaUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLFerramentaCidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFFerramentaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLFerramentaBairro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFFerramentaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLFerramentaRua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFFerramentaRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLFerramentaNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFFerramentaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjBAdicionarTinta() {
        return jBAdicionarTinta;
    }

    public JButton getjBBuscar() {
        return jBBuscar;
    }

    public JButton getjBCancelar() {
        return jBCancelar;
    }

    public JButton getjBProcurarPedido() {
        return jBProcurarPedido;
    }

    public JButton getjBRemoverTinta() {
        return jBRemoverTinta;
    }

    public JButton getjBSalvar() {
        return jBSalvar;
    }

    public JComboBox<String> getjCBSituacao() {
        return jCBSituacao;
    }

    public JTextArea getjTADescricaoPedido() {
        return jTADescricaoPedido;
    }

    public JTextField getjTFCEP() {
        return jTFCEP;
    }

    public JTextField getjTFCodigoPedido() {
        return jTFCodigoPedido;
    }

    public JTextField getjTFCodigoProducao() {
        return jTFCodigoProducao;
    }

    public JTextField getjTFCustoProducao() {
        return jTFCustoProducao;
    }

    public JTextField getjTFFerramentaBairro() {
        return jTFFerramentaBairro;
    }

    public JTextField getjTFFerramentaCidade() {
        return jTFFerramentaCidade;
    }

    public JTextField getjTFFerramentaNumero() {
        return jTFFerramentaNumero;
    }

    public JTextField getjTFFerramentaRua() {
        return jTFFerramentaRua;
    }

    public JTextField getjTFFerramentaUF() {
        return jTFFerramentaUF;
    }

    public JTable getjTTintasProduzidas() {
        return jTTintasProduzidas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionarTinta;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBProcurarPedido;
    private javax.swing.JButton jBRemoverTinta;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JComboBox<String> jCBSituacao;
    private javax.swing.JLabel jLCodigoPedido;
    private javax.swing.JLabel jLCodigoProducao5;
    private javax.swing.JLabel jLCodigodaTinta;
    private javax.swing.JLabel jLCustoProducao;
    private javax.swing.JLabel jLData;
    private javax.swing.JLabel jLFerramentaBairro;
    private javax.swing.JLabel jLFerramentaCEP;
    private javax.swing.JLabel jLFerramentaCidade;
    private javax.swing.JLabel jLFerramentaNumero;
    private javax.swing.JLabel jLFerramentaRua;
    private javax.swing.JLabel jLFerramentaUF;
    private javax.swing.JLabel jLQtdProducao1;
    private javax.swing.JLabel jLSituacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTADescricaoPedido;
    private javax.swing.JTextField jTFCEP;
    private javax.swing.JTextField jTFCodigoPedido;
    private javax.swing.JTextField jTFCodigoProducao;
    private javax.swing.JTextField jTFCustoProducao;
    private javax.swing.JTextField jTFFerramentaBairro;
    private javax.swing.JTextField jTFFerramentaCidade;
    private javax.swing.JTextField jTFFerramentaNumero;
    private javax.swing.JTextField jTFFerramentaRua;
    private javax.swing.JTextField jTFFerramentaUF;
    private javax.swing.JTable jTTintasProduzidas;
    // End of variables declaration//GEN-END:variables
}
